image: gitlab.pixl8.london:5005/utilities/pixl8-ci-env-docker-image
cache:
    paths:
        - tests/testbox/
        - assets/node_modules/

before_script:
  - box slack set defaults channel="team-elf-builds" title="Data API Gitlab build ${CI_JOB_ID} (${CI_COMMIT_REF_NAME})" titleLink="${CI_PROJECT_URL}/builds/${CI_JOB_ID}" author="${GITLAB_USER_EMAIL}"

stages:
  - test
  - package

unit_tests:
    stage: test
    except:
      - stable
    script: ./test.sh

package:
    stage: package
    only:
      - /v[0-9].*/
      - /release\-\.*/
    script:
      - ./build.sh
      - find ./build/*.zip -exec aws s3 cp {} s3://pixl8-packages/data-api/ \;
      - box slack send message color="good" message="Data API ${CI_COMMIT_REF_NAME} package and build complete!"
